Update section per legal advisory
neuralmagic/docs pull request #116
Opened 2022-11-10 18:51 UTC by rgreenberg1

also will need to update the new name of the NM License, soon

2022-11-16 17:49 UTC, jeanniefinks commented on src/content/products/deepsparse/community.mdx
> +Some source code, example files, and scripts included in the GitHub repository or directory are licensed under the [Apache License Version 2.0](https://github.com/neuralmagic/deepsparse/blob/main/LIC
```suggestion
Some source code, example files, and scripts included in the deepsparse GitHub repository or directory are licensed under the [Apache License Version 2.0](https://github.com/neuralmagic/deepsparse/blob/main/LICENSE) as noted.
```

2022-11-16 17:51 UTC, jeanniefinks commented on src/content/products/deepsparse/community.mdx
> +The Community Edition of the project's binary containing DeepSparse is licensed under the [Neural Magic Engine License.](https://github.com/neuralmagic/deepsparse/blob/main/LICENSE-NEURALMAGIC)
```suggestion
DeepSparse Community is licensed under the [Neural Magic DeepSparse Community License.](https://github.com/neuralmagic/deepsparse/blob/main/LICENSE-NEURALMAGIC)
```

2022-11-16 17:52 UTC, jeanniefinks commented on src/content/products/deepsparse/community.mdx
>  [The Enterprise Edition](https://docs.neuralmagic.com/products/deepsparse-ent) requires a Trial License or [can be fully licensed](https://neuralmagic.com/legal/master-software-license-and-service-ag
```suggestion
[DeepSparse Enterprise](https://docs.neuralmagic.com/products/deepsparse-ent) requires a Trial License or [can be fully licensed](https://neuralmagic.com/legal/master-software-license-and-service-agreement/) for production, commercial applications.
```

2022-11-16 17:53 UTC, jeanniefinks requested changes
minor edits

2022-11-17 15:05 UTC, jeanniefinks approved these changes

2022-11-17 19:59 UTC, Beth-Kosis approved these changes
These changes look fine.

2022-11-18 16:04 UTC, merged