added embedding extraction use case
neuralmagic/docs pull request #122
Opened 2022-11-16 00:42 UTC by rsnm2

@bfineran - docs site content for embedding extraction; draft

Let me know when you have some time tomorrow to fill in the details

2022-12-22 16:18 UTC, dbarbuzzi submitted a review, later dismissed

2022-12-22 16:51 UTC, jeanniefinks commented on src/content/use-cases/embedding-extraction.mdx
> +This page explains how to deploy an Embedding Extraction pipeline with DeepSparse.
```suggestion
This page explains how to deploy an Embedding Extraction Pipeline with DeepSparse.
```

2022-12-22 16:55 UTC, jeanniefinks submitted a review, later dismissed
1 p to P edit and I will approve this as a minor change

2022-12-22 17:25 UTC, jeanniefinks submitted a review, later dismissed

2022-12-22 19:11 UTC, bfineran requested changes
our repos standardize to not include documentation or example files directly under our `src/` directory.

Let's move these to `examples/embedding-extraction` OR potentially `src/deepsparse/pipelines/docs/embedding-extraction`

2022-12-30 21:42 UTC, jeanniefinks approved these changes
Reads well, no further comments here @rsnm2

2023-01-03 20:31 UTC, bfineran approved these changes

2023-01-04 20:42 UTC, merged