new branch without conflicts
neuralmagic/docs pull request #144
Opened 2023-01-11 17:28 UTC by rsnm2

2023-01-11 18:46 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +
If the items above are not titles or proper names, only the first word should be capitalized. For example: Slower performance than DeepSparse x86

2023-01-11 18:49 UTC, jeanniefinks reviewed
Also, there are a few things missing for me in terms of participation expectations and timeline. For example, here's a one-pager I did in 2020 for the engine which is meant to be an easy scannable page. It precedes a more formal playbook program content the user is to complete once we've accepted them into the product evaluation.  It could also be used for an email campaign. https://docs.google.com/document/d/1Q2cU8JVrW7NepwwGTX83LJUXY-I4O5bV/edit

2023-01-11 18:50 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +The General Release of DeepSparse for ARM will offer support for ARMv8+ devices, including server
General Release should be all lowercase.

2023-01-11 18:50 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +The General Release of DeepSparse for ARM will offer support for all models in ONNX format. However, the
General Release should be lowercase.

2023-01-11 18:52 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +ARM Alpha has been tested for accuracy on a subset a limited subset of models.
... on a limited subset of models.
I think "a subset" should be deleted.

2023-01-11 18:53 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +The following models have been tested for accuracy and performance with the DeepSparse ARM Alpha,
Remove the comma at the end of this line.

2023-01-11 18:54 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +At batch 64, ONNX runtime achieves 19 items/second running the standard BERT model.
ONNX Runtime
Because Runtime has an initial cap in previous instances, I'm assuming it's a proper name and should have an initial cap here as well.

2023-01-11 18:55 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +Making a request:
Here's an example of making a request:

2023-01-11 20:06 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +[Sign up for early access to the general release of DeepSparse on ARM](https://neuralmagic.com/deepsparse-arm-waitlist)
```suggestion
[Sign up for early access to the general release of DeepSparse on ARM](https://neuralmagic.com/deepsparse-arm-waitlist).
```

2023-01-11 20:07 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +Neural Magic is offering a $50 Amazon Gift card for a 30 minute conversation to discuss:
```suggestion
Neural Magic is offering a $50 Amazon gift card for a 30-minute conversation to discuss: 
```

2023-01-11 20:07 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +- Requests for features for DeepSparse on ARM
```suggestion
- Feature requests for DeepSparse on ARM
```

2023-01-11 20:09 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +[Reach out to set up time to discuss](https://neuralmagic.com/contact/)
```suggestion
[Reach out to schedule a discussion now](https://neuralmagic.com/contact/)!
```

2023-01-11 20:11 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +## Want to Particpate in Our Trial?
```suggestion
## Want To Participate in Our Trial?
```

2023-01-11 20:15 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +- **Long Compile Times** (compiling BERT on `M6g.16xlarge` takes XXX minutes)
don't forget to fill in the xxx minutes (even if it's an approximate range if that was the intent here; it's hard to know if you are going to fill it in)

2023-01-11 20:16 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +The following throughput statistics were generated using `deepsparse-nightly==xxx` on an `M6g.16xlarge` instance (64 cores):
which nightly was used here as it's not filled in?

2023-01-11 20:16 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +[Reach out to us to set up time to discuss your experience](https://neuralmagic.com/contact/)
Reach out to schedule a time to discuss your experience.

2023-01-11 20:16 UTC, Beth-Kosis commented on src/content/user-guide/arm-alpha.mdx
> +[Sign up for early access to the general release of DeepSparse on ARM](https://neuralmagic.com/deepsparse-arm-waitlist)
Period at the end of the sentence.

2023-01-11 20:17 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +    <img width="90%" src="https://raw.githubusercontent.com/neuralmagic/docs/arm-alpha-new/src/images/arm-benchmarks.png"/>
```suggestion
    <img width="90%" src="https://raw.githubusercontent.com/neuralmagic/docs/arm-alpha-new/src/images/arm-benchmarks.png" alt = "ARM benchmark with DeepSparse on a M6g.16xlarge instance"/>
```

2023-01-11 20:19 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +The General Release of DeepSparse for ARM will offer support for all models in ONNX format. However, the
```suggestion
The general release of DeepSparse for ARM will offer support for all models in ONNX format. However, the 
```

2023-01-11 20:19 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +ARM Alpha has been tested for accuracy on a subset a limited subset of models.
```suggestion
ARM Alpha has been tested for accuracy on a limited subset of models.
```

2023-01-11 20:20 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +The following models have been tested for accuracy and performance with the DeepSparse ARM Alpha,
```suggestion
The following models have been tested for accuracy and performance with the DeepSparse ARM Alpha  
```

2023-01-11 20:21 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +At batch 64, ONNX runtime achieves 19 items/second running the standard BERT model.
```suggestion
At batch 64, ONNX Runtime achieves 19 items/second running the standard BERT model.
```

2023-01-11 20:22 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +Making a request:
```suggestion
Here's an example of making a request:
```

2023-01-11 20:22 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +[Sign up for early access to the general release of DeepSparse on ARM](https://neuralmagic.com/deepsparse-arm-waitlist)
```suggestion
[Sign up for early access to the general release of DeepSparse on ARM](https://neuralmagic.com/deepsparse-arm-waitlist).
```

2023-01-11 20:24 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +[Reach out to us to set up time to discuss your experience](https://neuralmagic.com/contact/)
```suggestion
[Schedule a time to discuss your experience](https://neuralmagic.com/contact/).
```

2023-01-11 20:39 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +DeepSparse on ARM is currently in Alpha state.
```suggestion
DeepSparse on ARM is currently in alpha state. It has the following limitations:
```

2023-01-11 20:40 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +It has the following limitations:
```suggestion
```

2023-01-11 20:40 UTC, jeanniefinks commented on src/content/user-guide/arm-alpha.mdx
> +DeepSparse has Alpha support for ARM platforms! This page explains how to trial it.
```suggestion
DeepSparse has alpha support for ARM platforms! This page explains how to trial it.
```

2023-01-11 20:43 UTC, jeanniefinks requested changes
Made suggested edits.

2023-03-07 14:48 UTC, tlrmchlsmth approved these changes

2024-04-08 17:41 UTC, closed without merging