Docs 1.0 refactor installation
neuralmagic/docs pull request #83
Opened 2022-06-30 18:44 UTC by markurtz

2022-06-30 19:16 UTC, jeanniefinks commented on src/content/get-started/install.mdx
> +metaTitle: "Install DeepSparse Platform"
```suggestion
metaTitle: "Install Deep Sparse Platform"
```

2022-06-30 19:16 UTC, jeanniefinks commented on src/content/get-started/install.mdx
> +metaDescription: "Install instructions for the DeepSparse Platform including DeepSparse, SparseML, SparseZoo"
```suggestion
metaDescription: "Installation instructions for the Deep Sparse Platform including DeepSparse, SparseML, SparseZoo"
```

2022-07-01 00:41 UTC, jeanniefinks approved these changes

2022-07-11 18:48 UTC, jeanniefinks commented on src/content/get-started/install/deepsparse.mdx
> +metaDescription: "Installation instructions for the DeepSparse Inference Engine for neural network deployments."
```suggestion
metaDescription: "Installation instructions for the DeepSparse Engine for neural network deployments"
```

2022-07-11 18:50 UTC, jeanniefinks commented on src/content/get-started/install/sparsezoo.mdx
> +metaDescription: "Installation instructions for the SparseZoo sparse model repository."
```suggestion
metaDescription: "Installation instructions for the SparseZoo sparse model repository"
```

2022-07-11 18:52 UTC, jeanniefinks requested changes
Minor edits

2022-07-11 19:46 UTC, markurtz commented
@jeanniefinks edits merged in

2022-07-11 21:29 UTC, merged