Add docs getting started use a sparse model page
neuralmagic/docs pull request #84
Opened 2022-06-30 18:49 UTC by markurtz

2022-06-30 19:19 UTC, jeanniefinks commented on src/content/get-started/use-a-sparse-model.mdx
> +metaDescription: "Use a Sparse Model with DeepSparse to deploy for faster and cheaper inference on CPUs"
```suggestion
metaDescription: "Use a Sparse Model with DeepSparse Engine to deploy for faster and cheaper inference on CPUs"
```

2022-06-30 19:21 UTC, jeanniefinks commented on src/content/get-started/use-a-sparse-model.mdx
> +Here we'll be showing the performance gain on a DistilBERT trained on the SST2 dataset, going from dense to sparse to sparse quantized:
```suggestion
Here's the performance gain on a DistilBERT trained on the SST2 dataset, going from dense to sparse to sparse quantized:
```

2022-06-30 19:21 UTC, jeanniefinks commented on src/content/get-started/use-a-sparse-model.mdx
> +Here we'll be showing the performance gain on a YOLOv5s trained on the COCO dataset, going from dense to sparse to sparse quantized:
```suggestion
Here's the performance gain on a YOLOv5s trained on the COCO dataset, going from dense to sparse to sparse quantized:
```

2022-07-01 00:42 UTC, jeanniefinks requested changes
minor edits

2022-07-11 18:30 UTC, jeanniefinks commented on src/content/get-started/use-a-sparse-model.mdx
> +SparseZoo stubs are found throughout the documentation for the DeepSparse Platform in addition to the model pages on the [SparseZoo Website](https://sparsezoo.neuralmagic.com)
```suggestion
SparseZoo stubs are found throughout the documentation for the DeepSparse Platform in addition to the model pages on the [SparseZoo Website](https://sparsezoo.neuralmagic.com).
```
```suggestion
SparseZoo stubs are found throughout the documentation for the DeepSparse Platform in addition to the model pages on the [SparseZoo Website](https://sparsezoo.neuralmagic.com)
```

2022-07-11 18:32 UTC, jeanniefinks commented on src/content/get-started/use-a-sparse-model/object-detection.mdx
> +Next instantiate the pipeline and pass the image in using the images argument:
```suggestion
Next, instantiate the pipeline and pass the image in using the images argument:
```
```suggestion
Next instantiate the pipeline and pass the image in using the images argument:
```

2022-07-11 18:43 UTC, jeanniefinks requested changes
Minor edits needed

2022-07-11 19:47 UTC, markurtz commented
@jeanniefinks changes landed

2022-07-11 21:17 UTC, jeanniefinks approved these changes

2022-07-11 21:29 UTC, merged